# Generated by Django 5.1.4 on 2024-12-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_productitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category_image',
        ),
        migrations.AlterField(
            model_name='productitem',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
