# Generated by Django 5.1.4 on 2024-12-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_productcategory_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
