# Generated by Django 5.1.4 on 2025-01-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_wearing',
        ),
    ]
